/*
 * Generated by Bluespec Compiler (build 399b09c)
 * 
 * On Fri Apr  2 15:25:05 BST 2021
 * 
 */

/* Generation options: */
#ifndef __mkDivideTest_h__
#define __mkDivideTest_h__

#include "bluesim_types.h"
#include "bs_module.h"
#include "bluesim_primitives.h"
#include "bs_vcd.h"


/* Class declaration for the mkDivideTest module */
class MOD_mkDivideTest : public Module {
 
 /* Clock handles */
 private:
  tClock __clk_handle_0;
 
 /* Clock gate handles */
 public:
  tUInt8 *clk_gate[0];
 
 /* Instantiation parameters */
 public:
 
 /* Module state */
 public:
  MOD_ConfigReg<tUInt32> INST_acc;
  MOD_Fifo<tUWide> INST_fFirst;
  MOD_Fifo<tUWide> INST_fNext_0;
  MOD_Fifo<tUWide> INST_fNext_1;
  MOD_Fifo<tUWide> INST_fNext_10;
  MOD_Fifo<tUWide> INST_fNext_11;
  MOD_Fifo<tUWide> INST_fNext_12;
  MOD_Fifo<tUWide> INST_fNext_13;
  MOD_Fifo<tUWide> INST_fNext_14;
  MOD_Fifo<tUWide> INST_fNext_15;
  MOD_Fifo<tUWide> INST_fNext_16;
  MOD_Fifo<tUWide> INST_fNext_17;
  MOD_Fifo<tUWide> INST_fNext_18;
  MOD_Fifo<tUWide> INST_fNext_19;
  MOD_Fifo<tUWide> INST_fNext_2;
  MOD_Fifo<tUWide> INST_fNext_20;
  MOD_Fifo<tUWide> INST_fNext_21;
  MOD_Fifo<tUWide> INST_fNext_22;
  MOD_Fifo<tUWide> INST_fNext_23;
  MOD_Fifo<tUWide> INST_fNext_24;
  MOD_Fifo<tUWide> INST_fNext_25;
  MOD_Fifo<tUWide> INST_fNext_26;
  MOD_Fifo<tUWide> INST_fNext_27;
  MOD_Fifo<tUWide> INST_fNext_28;
  MOD_Fifo<tUWide> INST_fNext_3;
  MOD_Fifo<tUWide> INST_fNext_4;
  MOD_Fifo<tUWide> INST_fNext_5;
  MOD_Fifo<tUWide> INST_fNext_6;
  MOD_Fifo<tUWide> INST_fNext_7;
  MOD_Fifo<tUWide> INST_fNext_8;
  MOD_Fifo<tUWide> INST_fNext_9;
  MOD_Fifo<tUWide> INST_fRequest;
  MOD_Fifo<tUInt64> INST_fResponse;
  MOD_Fifo<tUWide> INST_fpu_div_fOperands_S0;
  MOD_Fifo<tUInt64> INST_fpu_div_fResult_S5;
  MOD_Fifo<tUWide> INST_fpu_div_fState_S1;
  MOD_Fifo<tUWide> INST_fpu_div_fState_S2;
  MOD_Fifo<tUWide> INST_fpu_div_fState_S3;
  MOD_Fifo<tUWide> INST_fpu_div_fState_S4;
  MOD_Fifo<tUWide> INST_fpu_madd_fOperand_S0;
  MOD_Fifo<tUInt64> INST_fpu_madd_fProd_S2;
  MOD_Fifo<tUInt64> INST_fpu_madd_fProd_S3;
  MOD_Fifo<tUInt64> INST_fpu_madd_fResult_S9;
  MOD_Fifo<tUWide> INST_fpu_madd_fState_S1;
  MOD_Fifo<tUWide> INST_fpu_madd_fState_S2;
  MOD_Fifo<tUWide> INST_fpu_madd_fState_S3;
  MOD_Fifo<tUWide> INST_fpu_madd_fState_S4;
  MOD_Fifo<tUWide> INST_fpu_madd_fState_S5;
  MOD_Fifo<tUWide> INST_fpu_madd_fState_S6;
  MOD_Fifo<tUWide> INST_fpu_madd_fState_S7;
  MOD_Fifo<tUWide> INST_fpu_madd_fState_S8;
  MOD_Reg<tUInt8> INST_m_count;
  MOD_Reg<tUInt8> INST_r_count;
 
 /* Constructor */
 public:
  MOD_mkDivideTest(tSimStateHdl simHdl, char const *name, Module *parent);
 
 /* Symbol init methods */
 private:
  void init_symbols_0();
 
 /* Reset signal definitions */
 private:
  tUInt8 PORT_RST_N;
 
 /* Port definitions */
 public:
 
 /* Publicly accessible definitions */
 public:
  tUInt8 DEF_b__h59804;
  tUWide DEF_fpu_div_fState_S1_first____d1741;
  tUWide DEF_fpu_div_fState_S2_first____d1756;
  tUInt8 DEF_b__h63509;
  tUInt8 DEF_fpu_div_fState_S1_first__741_BIT_164___d1742;
  tUInt8 DEF_fpu_div_fState_S2_first__756_BIT_80___d1757;
 
 /* Local definitions */
 private:
  tUInt8 DEF_unsigned_r_count_152___d2163;
  tUWide DEF_fpu_madd_fState_S1_first____d171;
  tUWide DEF_fpu_madd_fState_S5_first____d573;
  tUWide DEF_fNext_28_first____d1414;
  tUWide DEF_fNext_27_first____d1398;
  tUWide DEF_fNext_26_first____d1382;
  tUWide DEF_fNext_25_first____d1366;
  tUWide DEF_fNext_24_first____d1350;
  tUWide DEF_fNext_23_first____d1334;
  tUWide DEF_fNext_22_first____d1318;
  tUWide DEF_fNext_21_first____d1302;
  tUWide DEF_fNext_20_first____d1286;
  tUWide DEF_fNext_19_first____d1270;
  tUWide DEF_fNext_18_first____d1254;
  tUWide DEF_fNext_17_first____d1238;
  tUWide DEF_fNext_16_first____d1222;
  tUWide DEF_fNext_15_first____d1206;
  tUWide DEF_fNext_14_first____d1190;
  tUWide DEF_fNext_13_first____d1174;
  tUWide DEF_fNext_12_first____d1158;
  tUWide DEF_fNext_11_first____d1142;
  tUWide DEF_fNext_10_first____d1126;
  tUWide DEF_fNext_9_first____d1110;
  tUWide DEF_fNext_8_first____d1094;
  tUWide DEF_fNext_7_first____d1078;
  tUWide DEF_fNext_6_first____d1062;
  tUWide DEF_fNext_5_first____d1046;
  tUWide DEF_fNext_4_first____d1030;
  tUWide DEF_fNext_3_first____d1014;
  tUWide DEF_fNext_2_first____d998;
  tUWide DEF_fNext_1_first____d982;
  tUWide DEF_fNext_0_first____d966;
  tUWide DEF_fFirst_first____d950;
  tUWide DEF_fpu_madd_fState_S7_first____d623;
  tUWide DEF_fpu_madd_fState_S6_first____d607;
  tUWide DEF_fpu_madd_fState_S4_first____d519;
  tUWide DEF_fpu_div_fState_S3_first____d1793;
  tUWide DEF_fpu_madd_fOperand_S0_first____d4;
  tUWide DEF_fpu_madd_fState_S3_first____d199;
  tUWide DEF_fpu_madd_fState_S2_first____d188;
  tUWide DEF_fRequest_first____d942;
  tUWide DEF_fpu_madd_fState_S8_first____d816;
  tUWide DEF_fpu_div_fState_S4_first____d2036;
  tUWide DEF_fpu_div_fOperands_S0_first____d1433;
  tUWide DEF_fpu_div_fState_S1_first__741_BITS_91_TO_8___d1748;
  std::string DEF_IF_fpu_div_fResult_S5_first__169_BIT_36_170_TH_ETC___d2171;
  tUWide DEF_fpu_div_fOperands_S0_first__433_BITS_65_TO_58__ETC___d1738;
  tUWide DEF_fpu_div_fOperands_S0_first__433_BITS_2_TO_0_61_ETC___d1737;
  tUWide DEF_IF_fpu_madd_fOperand_S0_first_BIT_99_THEN_IF_f_ETC___d165;
  tUWide DEF_fpu_madd_fOperand_S0_first_BIT_99_AND_fpu_madd_ETC___d164;
  tUWide DEF__0b0_CONCAT_NOT_fpu_div_fOperands_S0_first__433_ETC___d1736;
  tUWide DEF_fpu_madd_fState_S4_first__19_BIT_107_20_CONCAT_ETC___d569;
  tUWide DEF_NOT_fpu_madd_fState_S4_first__19_BIT_65_26_EQ__ETC___d568;
  tUWide DEF_fNext_27_first__398_BITS_115_TO_87_399_CONCAT__ETC___d1410;
  tUWide DEF_fNext_26_first__382_BITS_115_TO_87_383_CONCAT__ETC___d1394;
  tUWide DEF_fNext_25_first__366_BITS_115_TO_87_367_CONCAT__ETC___d1378;
  tUWide DEF_fNext_24_first__350_BITS_115_TO_87_351_CONCAT__ETC___d1362;
  tUWide DEF_fNext_23_first__334_BITS_115_TO_87_335_CONCAT__ETC___d1346;
  tUWide DEF_fNext_22_first__318_BITS_115_TO_87_319_CONCAT__ETC___d1330;
  tUWide DEF_fNext_21_first__302_BITS_115_TO_87_303_CONCAT__ETC___d1314;
  tUWide DEF_fNext_20_first__286_BITS_115_TO_87_287_CONCAT__ETC___d1298;
  tUWide DEF_fNext_19_first__270_BITS_115_TO_87_271_CONCAT__ETC___d1282;
  tUWide DEF_fNext_18_first__254_BITS_115_TO_87_255_CONCAT__ETC___d1266;
  tUWide DEF_fNext_17_first__238_BITS_115_TO_87_239_CONCAT__ETC___d1250;
  tUWide DEF_fNext_16_first__222_BITS_115_TO_87_223_CONCAT__ETC___d1234;
  tUWide DEF_fNext_15_first__206_BITS_115_TO_87_207_CONCAT__ETC___d1218;
  tUWide DEF_fNext_14_first__190_BITS_115_TO_87_191_CONCAT__ETC___d1202;
  tUWide DEF_fNext_13_first__174_BITS_115_TO_87_175_CONCAT__ETC___d1186;
  tUWide DEF_fNext_12_first__158_BITS_115_TO_87_159_CONCAT__ETC___d1170;
  tUWide DEF_fNext_11_first__142_BITS_115_TO_87_143_CONCAT__ETC___d1154;
  tUWide DEF_fNext_10_first__126_BITS_115_TO_87_127_CONCAT__ETC___d1138;
  tUWide DEF_fNext_9_first__110_BITS_115_TO_87_111_CONCAT_f_ETC___d1122;
  tUWide DEF_fNext_8_first__094_BITS_115_TO_87_095_CONCAT_f_ETC___d1106;
  tUWide DEF_fNext_7_first__078_BITS_115_TO_87_079_CONCAT_f_ETC___d1090;
  tUWide DEF_fNext_6_first__062_BITS_115_TO_87_063_CONCAT_f_ETC___d1074;
  tUWide DEF_fNext_5_first__046_BITS_115_TO_87_047_CONCAT_f_ETC___d1058;
  tUWide DEF_fNext_4_first__030_BITS_115_TO_87_031_CONCAT_f_ETC___d1042;
  tUWide DEF_fNext_3_first__014_BITS_115_TO_87_015_CONCAT_f_ETC___d1026;
  tUWide DEF_fNext_2_first__98_BITS_115_TO_87_99_CONCAT_fNe_ETC___d1010;
  tUWide DEF_fNext_1_first__82_BITS_115_TO_87_83_CONCAT_fNe_ETC___d994;
  tUWide DEF_fNext_0_first__66_BITS_115_TO_87_67_CONCAT_fNe_ETC___d978;
  tUWide DEF__0_CONCAT_fRequest_first__42_BITS_27_TO_0_43_44_ETC___d946;
  tUWide DEF_fFirst_first__50_BITS_115_TO_87_51_CONCAT_fFir_ETC___d962;
  tUWide DEF_fpu_madd_fState_S5_first__73_BIT_119_74_CONCAT_ETC___d603;
  tUWide DEF_fpu_madd_fState_S5_first__73_BITS_75_TO_66_80__ETC___d602;
  tUWide DEF_fpu_madd_fState_S6_first__07_BIT_109_08_CONCAT_ETC___d619;
  tUWide DEF_fpu_madd_fState_S3_first__99_BIT_84_00_CONCAT__ETC___d515;
  tUWide DEF_fpu_div_fState_S2_first__756_BIT_80_757_CONCAT_ETC___d1789;
  tUWide DEF__1_CONCAT_acc_read__155_CONCAT_3660525779703719_ETC___d2156;
  tUWide DEF_fpu_madd_fState_S2_first__88_BIT_84_89_CONCAT__ETC___d193;
  tUWide DEF_fpu_madd_fState_S1_first__71_BIT_132_75_CONCAT_ETC___d179;
  tUWide DEF_fpu_div_fState_S1_first__741_BIT_164_742_CONCA_ETC___d1753;
  tUWide DEF_IF_NOT_fpu_madd_fState_S4_first__19_BIT_66_25__ETC___d567;
  tUWide DEF_fpu_madd_fState_S7_first__23_BIT_109_24_CONCAT_ETC___d812;
  tUWide DEF_IF_fpu_div_fState_S3_first__793_BITS_59_TO_52__ETC___d2032;
  tUInt8 DEF_m_count_164_PLUS_1___d2165;
 
 /* Rules */
 public:
  void RL_fpu_madd_s1_stage();
  void RL_fpu_madd_s2_stage();
  void RL_fpu_madd_s3_stage();
  void RL_fpu_madd_s4_stage();
  void RL_fpu_madd_s5_stage();
  void RL_fpu_madd_s6_stage();
  void RL_fpu_madd_s7_stage();
  void RL_fpu_madd_s8_stage();
  void RL_fpu_madd_s9_stage();
  void RL_start();
  void RL_work();
  void RL_work_1();
  void RL_work_2();
  void RL_work_3();
  void RL_work_4();
  void RL_work_5();
  void RL_work_6();
  void RL_work_7();
  void RL_work_8();
  void RL_work_9();
  void RL_work_10();
  void RL_work_11();
  void RL_work_12();
  void RL_work_13();
  void RL_work_14();
  void RL_work_15();
  void RL_work_16();
  void RL_work_17();
  void RL_work_18();
  void RL_work_19();
  void RL_work_20();
  void RL_work_21();
  void RL_work_22();
  void RL_work_23();
  void RL_work_24();
  void RL_work_25();
  void RL_work_26();
  void RL_work_27();
  void RL_work_28();
  void RL_finish();
  void RL_fpu_div_s1_stage();
  void RL_fpu_div_s2_stage();
  void RL_fpu_div_s3_stage();
  void RL_fpu_div_s4_stage();
  void RL_fpu_div_s5_stage();
  void RL_start_1();
  void RL_cycle();
  void RL_pipe_response_mul();
  void RL_pipe_response_mul_2();
  void RL_pipe_response_div();
 
 /* Methods */
 public:
 
 /* Reset routines */
 public:
  void reset_RST_N(tUInt8 ARG_rst_in);
 
 /* Static handles to reset routines */
 public:
 
 /* Pointers to reset fns in parent module for asserting output resets */
 private:
 
 /* Functions for the parent module to register its reset fns */
 public:
 
 /* Functions to set the elaborated clock id */
 public:
  void set_clk_0(char const *s);
 
 /* State dumping routine */
 public:
  void dump_state(unsigned int indent);
 
 /* VCD dumping routines */
 public:
  unsigned int dump_VCD_defs(unsigned int levels);
  void dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mkDivideTest &backing);
  void vcd_defs(tVCDDumpType dt, MOD_mkDivideTest &backing);
  void vcd_prims(tVCDDumpType dt, MOD_mkDivideTest &backing);
};

#endif /* ifndef __mkDivideTest_h__ */
