/*
 * Generated by Bluespec Compiler (build 399b09c)
 * 
 * On Mon Apr  5 19:20:02 BST 2021
 * 
 */

/* Generation options: */
#ifndef __mkZipReduceUnit_h__
#define __mkZipReduceUnit_h__

#include "bluesim_types.h"
#include "bs_module.h"
#include "bluesim_primitives.h"
#include "bs_vcd.h"


/* Class declaration for the mkZipReduceUnit module */
class MOD_mkZipReduceUnit : public Module {
 
 /* Clock handles */
 private:
  tClock __clk_handle_0;
 
 /* Clock gate handles */
 public:
  tUInt8 *clk_gate[0];
 
 /* Instantiation parameters */
 public:
 
 /* Module state */
 public:
  MOD_ConfigReg<tUInt32> INST_acc;
  MOD_Reg<tUInt32> INST_alloc_size;
  MOD_Fifo<tUWide> INST_fpu_add_fOperands_S0;
  MOD_Fifo<tUInt64> INST_fpu_add_fResult_S5;
  MOD_Fifo<tUWide> INST_fpu_add_fState_S1;
  MOD_Fifo<tUWide> INST_fpu_add_fState_S2;
  MOD_Fifo<tUWide> INST_fpu_add_fState_S3;
  MOD_Fifo<tUWide> INST_fpu_add_fState_S4;
  MOD_Fifo<tUWide> INST_fpu_madd_fOperand_S0;
  MOD_Fifo<tUInt64> INST_fpu_madd_fProd_S2;
  MOD_Fifo<tUInt64> INST_fpu_madd_fProd_S3;
  MOD_Fifo<tUInt64> INST_fpu_madd_fResult_S9;
  MOD_Fifo<tUWide> INST_fpu_madd_fState_S1;
  MOD_Fifo<tUWide> INST_fpu_madd_fState_S2;
  MOD_Fifo<tUWide> INST_fpu_madd_fState_S3;
  MOD_Fifo<tUWide> INST_fpu_madd_fState_S4;
  MOD_Fifo<tUWide> INST_fpu_madd_fState_S5;
  MOD_Fifo<tUWide> INST_fpu_madd_fState_S6;
  MOD_Fifo<tUWide> INST_fpu_madd_fState_S7;
  MOD_Fifo<tUWide> INST_fpu_madd_fState_S8;
  MOD_Reg<tUInt32> INST_m_count;
  MOD_Reg<tUInt32> INST_out_0;
  MOD_Reg<tUInt32> INST_out_1;
  MOD_Reg<tUInt32> INST_out_10;
  MOD_Reg<tUInt32> INST_out_11;
  MOD_Reg<tUInt32> INST_out_12;
  MOD_Reg<tUInt32> INST_out_13;
  MOD_Reg<tUInt32> INST_out_14;
  MOD_Reg<tUInt32> INST_out_15;
  MOD_Reg<tUInt32> INST_out_16;
  MOD_Reg<tUInt32> INST_out_17;
  MOD_Reg<tUInt32> INST_out_18;
  MOD_Reg<tUInt32> INST_out_19;
  MOD_Reg<tUInt32> INST_out_2;
  MOD_Reg<tUInt32> INST_out_20;
  MOD_Reg<tUInt32> INST_out_21;
  MOD_Reg<tUInt32> INST_out_22;
  MOD_Reg<tUInt32> INST_out_23;
  MOD_Reg<tUInt32> INST_out_24;
  MOD_Reg<tUInt32> INST_out_25;
  MOD_Reg<tUInt32> INST_out_26;
  MOD_Reg<tUInt32> INST_out_27;
  MOD_Reg<tUInt32> INST_out_28;
  MOD_Reg<tUInt32> INST_out_29;
  MOD_Reg<tUInt32> INST_out_3;
  MOD_Reg<tUInt32> INST_out_30;
  MOD_Reg<tUInt32> INST_out_31;
  MOD_Reg<tUInt32> INST_out_4;
  MOD_Reg<tUInt32> INST_out_5;
  MOD_Reg<tUInt32> INST_out_6;
  MOD_Reg<tUInt32> INST_out_7;
  MOD_Reg<tUInt32> INST_out_8;
  MOD_Reg<tUInt32> INST_out_9;
  MOD_Reg<tUInt32> INST_r_count;
  MOD_ConfigReg<tUInt8> INST_state;
 
 /* Constructor */
 public:
  MOD_mkZipReduceUnit(tSimStateHdl simHdl, char const *name, Module *parent);
 
 /* Symbol init methods */
 private:
  void init_symbols_0();
 
 /* Reset signal definitions */
 private:
  tUInt8 PORT_RST_N;
 
 /* Port definitions */
 public:
  tUWide PORT_request_put;
 
 /* Publicly accessible definitions */
 public:
  tUInt8 DEF_state_read____d1437;
  tUInt32 DEF_x__h45584;
  tUInt32 DEF_y__h45585;
  tUInt8 DEF_m_count_439_EQ_alloc_size_440___d1479;
 
 /* Local definitions */
 private:
  tUWide DEF_fpu_madd_fState_S1_first____d171;
  tUWide DEF_fpu_madd_fState_S5_first____d573;
  tUWide DEF_fpu_add_fState_S1_first____d1066;
  tUWide DEF_fpu_madd_fState_S7_first____d623;
  tUWide DEF_fpu_madd_fState_S6_first____d607;
  tUWide DEF_fpu_madd_fState_S4_first____d519;
  tUWide DEF_fpu_add_fState_S3_first____d1111;
  tUWide DEF_fpu_add_fState_S2_first____d1095;
  tUWide DEF_fpu_madd_fOperand_S0_first____d4;
  tUWide DEF_fpu_madd_fState_S3_first____d199;
  tUWide DEF_fpu_madd_fState_S2_first____d188;
  tUWide DEF_fpu_madd_fState_S8_first____d816;
  tUWide DEF_fpu_add_fState_S4_first____d1302;
  tUWide DEF_fpu_add_fOperands_S0_first____d942;
  tUInt32 DEF_acc_read____d1484;
  tUWide DEF_IF_fpu_madd_fOperand_S0_first_BIT_99_THEN_IF_f_ETC___d165;
  tUWide DEF_fpu_madd_fOperand_S0_first_BIT_99_AND_fpu_madd_ETC___d164;
  tUWide DEF_fpu_madd_fState_S4_first__19_BIT_107_20_CONCAT_ETC___d569;
  tUWide DEF_NOT_fpu_madd_fState_S4_first__19_BIT_65_26_EQ__ETC___d568;
  tUWide DEF_fpu_add_fOperands_S0_first__42_BITS_65_TO_58_4_ETC___d1062;
  tUWide DEF_fpu_madd_fState_S5_first__73_BIT_119_74_CONCAT_ETC___d603;
  tUWide DEF_fpu_madd_fState_S5_first__73_BITS_75_TO_66_80__ETC___d602;
  tUWide DEF_fpu_madd_fState_S6_first__07_BIT_109_08_CONCAT_ETC___d619;
  tUWide DEF_fpu_madd_fState_S3_first__99_BIT_84_00_CONCAT__ETC___d515;
  tUWide DEF_fpu_add_fState_S1_first__066_BIT_114_067_CONCA_ETC___d1091;
  tUWide DEF_fpu_add_fState_S2_first__095_BIT_106_096_CONCA_ETC___d1107;
  tUWide DEF__0_CONCAT_DONTCARE_CONCAT_request_put_BITS_63_T_ETC___d1631;
  tUWide DEF_fpu_madd_fState_S2_first__88_BIT_84_89_CONCAT__ETC___d193;
  tUWide DEF_fpu_madd_fState_S1_first__71_BIT_132_75_CONCAT_ETC___d179;
  tUWide DEF_IF_NOT_fpu_madd_fState_S4_first__19_BIT_66_25__ETC___d567;
  tUWide DEF_fpu_madd_fState_S7_first__23_BIT_109_24_CONCAT_ETC___d812;
  tUWide DEF_fpu_add_fState_S3_first__111_BIT_106_112_CONCA_ETC___d1298;
  tUWide DEF_acc_read__484_CONCAT_SEL_ARR_out_0_485_BIT_31__ETC___d1620;
  tUInt32 DEF_x__h45468;
 
 /* Rules */
 public:
  void RL_fpu_madd_s1_stage();
  void RL_fpu_madd_s2_stage();
  void RL_fpu_madd_s3_stage();
  void RL_fpu_madd_s4_stage();
  void RL_fpu_madd_s5_stage();
  void RL_fpu_madd_s6_stage();
  void RL_fpu_madd_s7_stage();
  void RL_fpu_madd_s8_stage();
  void RL_fpu_madd_s9_stage();
  void RL_fpu_add_s1_stage();
  void RL_fpu_add_s2_stage();
  void RL_fpu_add_s3_stage();
  void RL_fpu_add_s4_stage();
  void RL_fpu_add_s5_stage();
  void RL_rl_pipe_response_mul();
  void RL_rl_end_multiply();
  void RL_rl_start_acc();
  void RL_rl_pipe_response_add();
 
 /* Methods */
 public:
  void METH_request_put(tUWide ARG_request_put);
  tUInt8 METH_RDY_request_put();
  tUInt32 METH_response_get();
  tUInt8 METH_RDY_response_get();
 
 /* Reset routines */
 public:
  void reset_RST_N(tUInt8 ARG_rst_in);
 
 /* Static handles to reset routines */
 public:
 
 /* Pointers to reset fns in parent module for asserting output resets */
 private:
 
 /* Functions for the parent module to register its reset fns */
 public:
 
 /* Functions to set the elaborated clock id */
 public:
  void set_clk_0(char const *s);
 
 /* State dumping routine */
 public:
  void dump_state(unsigned int indent);
 
 /* VCD dumping routines */
 public:
  unsigned int dump_VCD_defs(unsigned int levels);
  void dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mkZipReduceUnit &backing);
  void vcd_defs(tVCDDumpType dt, MOD_mkZipReduceUnit &backing);
  void vcd_prims(tVCDDumpType dt, MOD_mkZipReduceUnit &backing);
};

#endif /* ifndef __mkZipReduceUnit_h__ */
