/*
 * Generated by Bluespec Compiler (build 399b09c)
 * 
 * On Fri Apr  2 15:25:05 BST 2021
 * 
 */
#include "bluesim_primitives.h"
#include "model_mkDivideTest.h"

#include <cstdlib>
#include <time.h>
#include "bluesim_kernel_api.h"
#include "bs_vcd.h"
#include "bs_reset.h"


/* Constructor */
MODEL_mkDivideTest::MODEL_mkDivideTest()
{
  mkDivideTest_instance = NULL;
}

/* Function for creating a new model */
void * new_MODEL_mkDivideTest()
{
  MODEL_mkDivideTest *model = new MODEL_mkDivideTest();
  return (void *)(model);
}

/* Schedule functions */

static void schedule_posedge_CLK(tSimStateHdl simHdl, void *instance_ptr)
       {
	 MOD_mkDivideTest &INST_top = *((MOD_mkDivideTest *)(instance_ptr));
	 tUInt8 DEF_INST_top_DEF_fpu_madd_fOperand_S0_i_notFull____d2149;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_fpu_madd_s1_stage;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_fpu_madd_s1_stage;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_fpu_madd_s2_stage;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_fpu_madd_s2_stage;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_fpu_madd_s3_stage;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_fpu_madd_s3_stage;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_fpu_madd_s4_stage;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_fpu_madd_s4_stage;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_fpu_madd_s5_stage;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_fpu_madd_s5_stage;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_fpu_madd_s6_stage;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_fpu_madd_s6_stage;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_fpu_madd_s7_stage;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_fpu_madd_s7_stage;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_fpu_madd_s8_stage;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_fpu_madd_s8_stage;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_fpu_madd_s9_stage;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_fpu_madd_s9_stage;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_start;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_start;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_work;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_work;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_work_1;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_work_1;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_work_2;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_work_2;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_work_3;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_work_3;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_work_4;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_work_4;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_work_5;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_work_5;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_work_6;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_work_6;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_work_7;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_work_7;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_work_8;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_work_8;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_work_9;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_work_9;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_work_10;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_work_10;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_work_11;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_work_11;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_work_12;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_work_12;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_work_13;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_work_13;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_work_14;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_work_14;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_work_15;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_work_15;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_work_16;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_work_16;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_work_17;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_work_17;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_work_18;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_work_18;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_work_19;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_work_19;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_work_20;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_work_20;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_work_21;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_work_21;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_work_22;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_work_22;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_work_23;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_work_23;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_work_24;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_work_24;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_work_25;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_work_25;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_work_26;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_work_26;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_work_27;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_work_27;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_work_28;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_work_28;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_finish;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_finish;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_fpu_div_s1_stage;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_fpu_div_s1_stage;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_fpu_div_s2_stage;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_fpu_div_s2_stage;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_fpu_div_s3_stage;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_fpu_div_s3_stage;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_fpu_div_s4_stage;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_fpu_div_s4_stage;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_fpu_div_s5_stage;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_fpu_div_s5_stage;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_start_1;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_start_1;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_cycle;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_cycle;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_pipe_response_mul;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_pipe_response_mul;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_pipe_response_mul_2;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_pipe_response_mul_2;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_pipe_response_div;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_pipe_response_div;
	 INST_top.DEF_b__h59804 = INST_top.INST_r_count.METH_read();
	 DEF_INST_top_DEF_CAN_FIRE_RL_cycle = !((INST_top.DEF_b__h59804) == (tUInt8)255u);
	 DEF_INST_top_DEF_WILL_FIRE_RL_cycle = DEF_INST_top_DEF_CAN_FIRE_RL_cycle;
	 DEF_INST_top_DEF_CAN_FIRE_RL_pipe_response_div = INST_top.INST_fpu_div_fResult_S5.METH_i_notEmpty();
	 DEF_INST_top_DEF_WILL_FIRE_RL_pipe_response_div = DEF_INST_top_DEF_CAN_FIRE_RL_pipe_response_div;
	 DEF_INST_top_DEF_CAN_FIRE_RL_pipe_response_mul = INST_top.INST_fpu_madd_fResult_S9.METH_i_notEmpty();
	 DEF_INST_top_DEF_WILL_FIRE_RL_pipe_response_mul = DEF_INST_top_DEF_CAN_FIRE_RL_pipe_response_mul;
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_pipe_response_mul)
	   INST_top.RL_pipe_response_mul();
	 DEF_INST_top_DEF_CAN_FIRE_RL_fpu_madd_s9_stage = INST_top.INST_fpu_madd_fState_S8.METH_i_notEmpty() && INST_top.INST_fpu_madd_fResult_S9.METH_i_notFull();
	 DEF_INST_top_DEF_WILL_FIRE_RL_fpu_madd_s9_stage = DEF_INST_top_DEF_CAN_FIRE_RL_fpu_madd_s9_stage;
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_fpu_madd_s9_stage)
	   INST_top.RL_fpu_madd_s9_stage();
	 DEF_INST_top_DEF_CAN_FIRE_RL_fpu_madd_s8_stage = INST_top.INST_fpu_madd_fState_S7.METH_i_notEmpty() && INST_top.INST_fpu_madd_fState_S8.METH_i_notFull();
	 DEF_INST_top_DEF_WILL_FIRE_RL_fpu_madd_s8_stage = DEF_INST_top_DEF_CAN_FIRE_RL_fpu_madd_s8_stage;
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_fpu_madd_s8_stage)
	   INST_top.RL_fpu_madd_s8_stage();
	 DEF_INST_top_DEF_CAN_FIRE_RL_fpu_madd_s7_stage = INST_top.INST_fpu_madd_fState_S6.METH_i_notEmpty() && INST_top.INST_fpu_madd_fState_S7.METH_i_notFull();
	 DEF_INST_top_DEF_WILL_FIRE_RL_fpu_madd_s7_stage = DEF_INST_top_DEF_CAN_FIRE_RL_fpu_madd_s7_stage;
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_fpu_madd_s7_stage)
	   INST_top.RL_fpu_madd_s7_stage();
	 DEF_INST_top_DEF_CAN_FIRE_RL_fpu_madd_s6_stage = INST_top.INST_fpu_madd_fState_S5.METH_i_notEmpty() && INST_top.INST_fpu_madd_fState_S6.METH_i_notFull();
	 DEF_INST_top_DEF_WILL_FIRE_RL_fpu_madd_s6_stage = DEF_INST_top_DEF_CAN_FIRE_RL_fpu_madd_s6_stage;
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_fpu_madd_s6_stage)
	   INST_top.RL_fpu_madd_s6_stage();
	 DEF_INST_top_DEF_CAN_FIRE_RL_fpu_madd_s5_stage = INST_top.INST_fpu_madd_fState_S4.METH_i_notEmpty() && INST_top.INST_fpu_madd_fState_S5.METH_i_notFull();
	 DEF_INST_top_DEF_WILL_FIRE_RL_fpu_madd_s5_stage = DEF_INST_top_DEF_CAN_FIRE_RL_fpu_madd_s5_stage;
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_fpu_madd_s5_stage)
	   INST_top.RL_fpu_madd_s5_stage();
	 DEF_INST_top_DEF_CAN_FIRE_RL_fpu_madd_s4_stage = INST_top.INST_fpu_madd_fState_S3.METH_i_notEmpty() && (INST_top.INST_fpu_madd_fProd_S3.METH_i_notEmpty() && INST_top.INST_fpu_madd_fState_S4.METH_i_notFull());
	 DEF_INST_top_DEF_WILL_FIRE_RL_fpu_madd_s4_stage = DEF_INST_top_DEF_CAN_FIRE_RL_fpu_madd_s4_stage;
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_fpu_madd_s4_stage)
	   INST_top.RL_fpu_madd_s4_stage();
	 DEF_INST_top_DEF_CAN_FIRE_RL_fpu_madd_s3_stage = INST_top.INST_fpu_madd_fState_S2.METH_i_notEmpty() && (INST_top.INST_fpu_madd_fProd_S2.METH_i_notEmpty() && (INST_top.INST_fpu_madd_fProd_S3.METH_i_notFull() && INST_top.INST_fpu_madd_fState_S3.METH_i_notFull()));
	 DEF_INST_top_DEF_WILL_FIRE_RL_fpu_madd_s3_stage = DEF_INST_top_DEF_CAN_FIRE_RL_fpu_madd_s3_stage;
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_fpu_madd_s3_stage)
	   INST_top.RL_fpu_madd_s3_stage();
	 DEF_INST_top_DEF_CAN_FIRE_RL_fpu_madd_s2_stage = INST_top.INST_fpu_madd_fState_S1.METH_i_notEmpty() && (INST_top.INST_fpu_madd_fProd_S2.METH_i_notFull() && INST_top.INST_fpu_madd_fState_S2.METH_i_notFull());
	 DEF_INST_top_DEF_WILL_FIRE_RL_fpu_madd_s2_stage = DEF_INST_top_DEF_CAN_FIRE_RL_fpu_madd_s2_stage;
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_fpu_madd_s2_stage)
	   INST_top.RL_fpu_madd_s2_stage();
	 DEF_INST_top_DEF_CAN_FIRE_RL_fpu_madd_s1_stage = INST_top.INST_fpu_madd_fOperand_S0.METH_i_notEmpty() && INST_top.INST_fpu_madd_fState_S1.METH_i_notFull();
	 DEF_INST_top_DEF_WILL_FIRE_RL_fpu_madd_s1_stage = DEF_INST_top_DEF_CAN_FIRE_RL_fpu_madd_s1_stage;
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_fpu_madd_s1_stage)
	   INST_top.RL_fpu_madd_s1_stage();
	 INST_top.DEF_b__h63509 = INST_top.INST_m_count.METH_read();
	 DEF_INST_top_DEF_fpu_madd_fOperand_S0_i_notFull____d2149 = INST_top.INST_fpu_madd_fOperand_S0.METH_i_notFull();
	 DEF_INST_top_DEF_CAN_FIRE_RL_pipe_response_mul_2 = DEF_INST_top_DEF_fpu_madd_fOperand_S0_i_notFull____d2149 && (INST_top.DEF_b__h63509) == (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_pipe_response_mul_2 = DEF_INST_top_DEF_CAN_FIRE_RL_pipe_response_mul_2 && !DEF_INST_top_DEF_WILL_FIRE_RL_pipe_response_mul;
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_pipe_response_div)
	   INST_top.RL_pipe_response_div();
	 DEF_INST_top_DEF_CAN_FIRE_RL_fpu_div_s5_stage = INST_top.INST_fpu_div_fState_S4.METH_i_notEmpty() && INST_top.INST_fpu_div_fResult_S5.METH_i_notFull();
	 DEF_INST_top_DEF_WILL_FIRE_RL_fpu_div_s5_stage = DEF_INST_top_DEF_CAN_FIRE_RL_fpu_div_s5_stage;
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_fpu_div_s5_stage)
	   INST_top.RL_fpu_div_s5_stage();
	 DEF_INST_top_DEF_CAN_FIRE_RL_fpu_div_s4_stage = INST_top.INST_fpu_div_fState_S3.METH_i_notEmpty() && INST_top.INST_fpu_div_fState_S4.METH_i_notFull();
	 DEF_INST_top_DEF_WILL_FIRE_RL_fpu_div_s4_stage = DEF_INST_top_DEF_CAN_FIRE_RL_fpu_div_s4_stage;
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_fpu_div_s4_stage)
	   INST_top.RL_fpu_div_s4_stage();
	 INST_top.DEF_fpu_div_fState_S2_first____d1756 = INST_top.INST_fpu_div_fState_S2.METH_first();
	 INST_top.DEF_fpu_div_fState_S2_first__756_BIT_80___d1757 = INST_top.DEF_fpu_div_fState_S2_first____d1756.get_bits_in_word8(2u,
																    16u,
																    1u);
	 DEF_INST_top_DEF_CAN_FIRE_RL_fpu_div_s3_stage = INST_top.INST_fpu_div_fState_S2.METH_i_notEmpty() && (INST_top.INST_fpu_div_fState_S3.METH_i_notFull() && (INST_top.DEF_fpu_div_fState_S2_first__756_BIT_80___d1757 || INST_top.INST_fResponse.METH_i_notEmpty()));
	 DEF_INST_top_DEF_WILL_FIRE_RL_fpu_div_s3_stage = DEF_INST_top_DEF_CAN_FIRE_RL_fpu_div_s3_stage;
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_fpu_div_s3_stage)
	   INST_top.RL_fpu_div_s3_stage();
	 DEF_INST_top_DEF_CAN_FIRE_RL_finish = INST_top.INST_fNext_28.METH_i_notEmpty() && INST_top.INST_fResponse.METH_i_notFull();
	 DEF_INST_top_DEF_WILL_FIRE_RL_finish = DEF_INST_top_DEF_CAN_FIRE_RL_finish;
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_finish)
	   INST_top.RL_finish();
	 DEF_INST_top_DEF_CAN_FIRE_RL_work_28 = INST_top.INST_fNext_27.METH_i_notEmpty() && INST_top.INST_fNext_28.METH_i_notFull();
	 DEF_INST_top_DEF_WILL_FIRE_RL_work_28 = DEF_INST_top_DEF_CAN_FIRE_RL_work_28;
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_pipe_response_mul_2)
	   INST_top.RL_pipe_response_mul_2();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_work_28)
	   INST_top.RL_work_28();
	 DEF_INST_top_DEF_CAN_FIRE_RL_work_27 = INST_top.INST_fNext_26.METH_i_notEmpty() && INST_top.INST_fNext_27.METH_i_notFull();
	 DEF_INST_top_DEF_WILL_FIRE_RL_work_27 = DEF_INST_top_DEF_CAN_FIRE_RL_work_27;
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_work_27)
	   INST_top.RL_work_27();
	 DEF_INST_top_DEF_CAN_FIRE_RL_work_26 = INST_top.INST_fNext_25.METH_i_notEmpty() && INST_top.INST_fNext_26.METH_i_notFull();
	 DEF_INST_top_DEF_WILL_FIRE_RL_work_26 = DEF_INST_top_DEF_CAN_FIRE_RL_work_26;
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_work_26)
	   INST_top.RL_work_26();
	 DEF_INST_top_DEF_CAN_FIRE_RL_work_25 = INST_top.INST_fNext_24.METH_i_notEmpty() && INST_top.INST_fNext_25.METH_i_notFull();
	 DEF_INST_top_DEF_WILL_FIRE_RL_work_25 = DEF_INST_top_DEF_CAN_FIRE_RL_work_25;
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_work_25)
	   INST_top.RL_work_25();
	 DEF_INST_top_DEF_CAN_FIRE_RL_work_24 = INST_top.INST_fNext_23.METH_i_notEmpty() && INST_top.INST_fNext_24.METH_i_notFull();
	 DEF_INST_top_DEF_WILL_FIRE_RL_work_24 = DEF_INST_top_DEF_CAN_FIRE_RL_work_24;
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_work_24)
	   INST_top.RL_work_24();
	 DEF_INST_top_DEF_CAN_FIRE_RL_work_23 = INST_top.INST_fNext_22.METH_i_notEmpty() && INST_top.INST_fNext_23.METH_i_notFull();
	 DEF_INST_top_DEF_WILL_FIRE_RL_work_23 = DEF_INST_top_DEF_CAN_FIRE_RL_work_23;
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_work_23)
	   INST_top.RL_work_23();
	 DEF_INST_top_DEF_CAN_FIRE_RL_work_22 = INST_top.INST_fNext_21.METH_i_notEmpty() && INST_top.INST_fNext_22.METH_i_notFull();
	 DEF_INST_top_DEF_WILL_FIRE_RL_work_22 = DEF_INST_top_DEF_CAN_FIRE_RL_work_22;
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_work_22)
	   INST_top.RL_work_22();
	 DEF_INST_top_DEF_CAN_FIRE_RL_work_21 = INST_top.INST_fNext_20.METH_i_notEmpty() && INST_top.INST_fNext_21.METH_i_notFull();
	 DEF_INST_top_DEF_WILL_FIRE_RL_work_21 = DEF_INST_top_DEF_CAN_FIRE_RL_work_21;
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_work_21)
	   INST_top.RL_work_21();
	 DEF_INST_top_DEF_CAN_FIRE_RL_work_20 = INST_top.INST_fNext_19.METH_i_notEmpty() && INST_top.INST_fNext_20.METH_i_notFull();
	 DEF_INST_top_DEF_WILL_FIRE_RL_work_20 = DEF_INST_top_DEF_CAN_FIRE_RL_work_20;
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_work_20)
	   INST_top.RL_work_20();
	 DEF_INST_top_DEF_CAN_FIRE_RL_work_19 = INST_top.INST_fNext_18.METH_i_notEmpty() && INST_top.INST_fNext_19.METH_i_notFull();
	 DEF_INST_top_DEF_WILL_FIRE_RL_work_19 = DEF_INST_top_DEF_CAN_FIRE_RL_work_19;
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_work_19)
	   INST_top.RL_work_19();
	 DEF_INST_top_DEF_CAN_FIRE_RL_work_18 = INST_top.INST_fNext_17.METH_i_notEmpty() && INST_top.INST_fNext_18.METH_i_notFull();
	 DEF_INST_top_DEF_WILL_FIRE_RL_work_18 = DEF_INST_top_DEF_CAN_FIRE_RL_work_18;
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_work_18)
	   INST_top.RL_work_18();
	 DEF_INST_top_DEF_CAN_FIRE_RL_work_17 = INST_top.INST_fNext_16.METH_i_notEmpty() && INST_top.INST_fNext_17.METH_i_notFull();
	 DEF_INST_top_DEF_WILL_FIRE_RL_work_17 = DEF_INST_top_DEF_CAN_FIRE_RL_work_17;
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_work_17)
	   INST_top.RL_work_17();
	 DEF_INST_top_DEF_CAN_FIRE_RL_work_16 = INST_top.INST_fNext_15.METH_i_notEmpty() && INST_top.INST_fNext_16.METH_i_notFull();
	 DEF_INST_top_DEF_WILL_FIRE_RL_work_16 = DEF_INST_top_DEF_CAN_FIRE_RL_work_16;
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_work_16)
	   INST_top.RL_work_16();
	 DEF_INST_top_DEF_CAN_FIRE_RL_work_15 = INST_top.INST_fNext_14.METH_i_notEmpty() && INST_top.INST_fNext_15.METH_i_notFull();
	 DEF_INST_top_DEF_WILL_FIRE_RL_work_15 = DEF_INST_top_DEF_CAN_FIRE_RL_work_15;
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_work_15)
	   INST_top.RL_work_15();
	 DEF_INST_top_DEF_CAN_FIRE_RL_work_14 = INST_top.INST_fNext_13.METH_i_notEmpty() && INST_top.INST_fNext_14.METH_i_notFull();
	 DEF_INST_top_DEF_WILL_FIRE_RL_work_14 = DEF_INST_top_DEF_CAN_FIRE_RL_work_14;
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_work_14)
	   INST_top.RL_work_14();
	 DEF_INST_top_DEF_CAN_FIRE_RL_work_13 = INST_top.INST_fNext_12.METH_i_notEmpty() && INST_top.INST_fNext_13.METH_i_notFull();
	 DEF_INST_top_DEF_WILL_FIRE_RL_work_13 = DEF_INST_top_DEF_CAN_FIRE_RL_work_13;
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_work_13)
	   INST_top.RL_work_13();
	 DEF_INST_top_DEF_CAN_FIRE_RL_work_12 = INST_top.INST_fNext_11.METH_i_notEmpty() && INST_top.INST_fNext_12.METH_i_notFull();
	 DEF_INST_top_DEF_WILL_FIRE_RL_work_12 = DEF_INST_top_DEF_CAN_FIRE_RL_work_12;
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_work_12)
	   INST_top.RL_work_12();
	 DEF_INST_top_DEF_CAN_FIRE_RL_work_11 = INST_top.INST_fNext_10.METH_i_notEmpty() && INST_top.INST_fNext_11.METH_i_notFull();
	 DEF_INST_top_DEF_WILL_FIRE_RL_work_11 = DEF_INST_top_DEF_CAN_FIRE_RL_work_11;
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_work_11)
	   INST_top.RL_work_11();
	 DEF_INST_top_DEF_CAN_FIRE_RL_work_10 = INST_top.INST_fNext_9.METH_i_notEmpty() && INST_top.INST_fNext_10.METH_i_notFull();
	 DEF_INST_top_DEF_WILL_FIRE_RL_work_10 = DEF_INST_top_DEF_CAN_FIRE_RL_work_10;
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_work_10)
	   INST_top.RL_work_10();
	 DEF_INST_top_DEF_CAN_FIRE_RL_work_9 = INST_top.INST_fNext_8.METH_i_notEmpty() && INST_top.INST_fNext_9.METH_i_notFull();
	 DEF_INST_top_DEF_WILL_FIRE_RL_work_9 = DEF_INST_top_DEF_CAN_FIRE_RL_work_9;
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_work_9)
	   INST_top.RL_work_9();
	 DEF_INST_top_DEF_CAN_FIRE_RL_work_8 = INST_top.INST_fNext_7.METH_i_notEmpty() && INST_top.INST_fNext_8.METH_i_notFull();
	 DEF_INST_top_DEF_WILL_FIRE_RL_work_8 = DEF_INST_top_DEF_CAN_FIRE_RL_work_8;
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_work_8)
	   INST_top.RL_work_8();
	 DEF_INST_top_DEF_CAN_FIRE_RL_work_7 = INST_top.INST_fNext_6.METH_i_notEmpty() && INST_top.INST_fNext_7.METH_i_notFull();
	 DEF_INST_top_DEF_WILL_FIRE_RL_work_7 = DEF_INST_top_DEF_CAN_FIRE_RL_work_7;
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_work_7)
	   INST_top.RL_work_7();
	 DEF_INST_top_DEF_CAN_FIRE_RL_work_6 = INST_top.INST_fNext_5.METH_i_notEmpty() && INST_top.INST_fNext_6.METH_i_notFull();
	 DEF_INST_top_DEF_WILL_FIRE_RL_work_6 = DEF_INST_top_DEF_CAN_FIRE_RL_work_6;
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_work_6)
	   INST_top.RL_work_6();
	 DEF_INST_top_DEF_CAN_FIRE_RL_work_5 = INST_top.INST_fNext_4.METH_i_notEmpty() && INST_top.INST_fNext_5.METH_i_notFull();
	 DEF_INST_top_DEF_WILL_FIRE_RL_work_5 = DEF_INST_top_DEF_CAN_FIRE_RL_work_5;
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_work_5)
	   INST_top.RL_work_5();
	 DEF_INST_top_DEF_CAN_FIRE_RL_work_4 = INST_top.INST_fNext_3.METH_i_notEmpty() && INST_top.INST_fNext_4.METH_i_notFull();
	 DEF_INST_top_DEF_WILL_FIRE_RL_work_4 = DEF_INST_top_DEF_CAN_FIRE_RL_work_4;
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_work_4)
	   INST_top.RL_work_4();
	 DEF_INST_top_DEF_CAN_FIRE_RL_work_3 = INST_top.INST_fNext_2.METH_i_notEmpty() && INST_top.INST_fNext_3.METH_i_notFull();
	 DEF_INST_top_DEF_WILL_FIRE_RL_work_3 = DEF_INST_top_DEF_CAN_FIRE_RL_work_3;
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_work_3)
	   INST_top.RL_work_3();
	 DEF_INST_top_DEF_CAN_FIRE_RL_work_2 = INST_top.INST_fNext_1.METH_i_notEmpty() && INST_top.INST_fNext_2.METH_i_notFull();
	 DEF_INST_top_DEF_WILL_FIRE_RL_work_2 = DEF_INST_top_DEF_CAN_FIRE_RL_work_2;
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_work_2)
	   INST_top.RL_work_2();
	 DEF_INST_top_DEF_CAN_FIRE_RL_work_1 = INST_top.INST_fNext_0.METH_i_notEmpty() && INST_top.INST_fNext_1.METH_i_notFull();
	 DEF_INST_top_DEF_WILL_FIRE_RL_work_1 = DEF_INST_top_DEF_CAN_FIRE_RL_work_1;
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_work_1)
	   INST_top.RL_work_1();
	 DEF_INST_top_DEF_CAN_FIRE_RL_work = INST_top.INST_fFirst.METH_i_notEmpty() && INST_top.INST_fNext_0.METH_i_notFull();
	 DEF_INST_top_DEF_WILL_FIRE_RL_work = DEF_INST_top_DEF_CAN_FIRE_RL_work;
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_work)
	   INST_top.RL_work();
	 DEF_INST_top_DEF_CAN_FIRE_RL_start = INST_top.INST_fRequest.METH_i_notEmpty() && INST_top.INST_fFirst.METH_i_notFull();
	 DEF_INST_top_DEF_WILL_FIRE_RL_start = DEF_INST_top_DEF_CAN_FIRE_RL_start;
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_start)
	   INST_top.RL_start();
	 INST_top.DEF_fpu_div_fState_S1_first____d1741 = INST_top.INST_fpu_div_fState_S1.METH_first();
	 INST_top.DEF_fpu_div_fState_S1_first__741_BIT_164___d1742 = INST_top.DEF_fpu_div_fState_S1_first____d1741.get_bits_in_word8(5u,
																     4u,
																     1u);
	 DEF_INST_top_DEF_CAN_FIRE_RL_fpu_div_s2_stage = INST_top.INST_fpu_div_fState_S1.METH_i_notEmpty() && (INST_top.INST_fpu_div_fState_S2.METH_i_notFull() && (INST_top.DEF_fpu_div_fState_S1_first__741_BIT_164___d1742 || INST_top.INST_fRequest.METH_i_notFull()));
	 DEF_INST_top_DEF_WILL_FIRE_RL_fpu_div_s2_stage = DEF_INST_top_DEF_CAN_FIRE_RL_fpu_div_s2_stage;
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_fpu_div_s2_stage)
	   INST_top.RL_fpu_div_s2_stage();
	 DEF_INST_top_DEF_CAN_FIRE_RL_fpu_div_s1_stage = INST_top.INST_fpu_div_fOperands_S0.METH_i_notEmpty() && INST_top.INST_fpu_div_fState_S1.METH_i_notFull();
	 DEF_INST_top_DEF_WILL_FIRE_RL_fpu_div_s1_stage = DEF_INST_top_DEF_CAN_FIRE_RL_fpu_div_s1_stage;
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_fpu_div_s1_stage)
	   INST_top.RL_fpu_div_s1_stage();
	 DEF_INST_top_DEF_CAN_FIRE_RL_start_1 = (DEF_INST_top_DEF_fpu_madd_fOperand_S0_i_notFull____d2149 && INST_top.INST_fpu_div_fOperands_S0.METH_i_notFull()) && (INST_top.DEF_b__h59804) == (tUInt8)0u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_start_1 = DEF_INST_top_DEF_CAN_FIRE_RL_start_1 && !DEF_INST_top_DEF_WILL_FIRE_RL_pipe_response_mul_2;
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_start_1)
	   INST_top.RL_start_1();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_cycle)
	   INST_top.RL_cycle();
	 if (do_reset_ticks(simHdl))
	 {
	   INST_top.INST_r_count.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_m_count.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_fpu_madd_fOperand_S0.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_fpu_madd_fState_S1.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_fpu_madd_fState_S2.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_fpu_madd_fProd_S2.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_fpu_madd_fState_S3.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_fpu_madd_fProd_S3.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_fpu_madd_fState_S4.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_fpu_madd_fState_S5.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_fpu_madd_fState_S6.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_fpu_madd_fState_S7.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_fpu_madd_fState_S8.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_fpu_madd_fResult_S9.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_fRequest.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_fResponse.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_fFirst.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_fNext_0.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_fNext_1.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_fNext_2.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_fNext_3.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_fNext_4.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_fNext_5.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_fNext_6.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_fNext_7.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_fNext_8.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_fNext_9.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_fNext_10.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_fNext_11.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_fNext_12.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_fNext_13.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_fNext_14.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_fNext_15.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_fNext_16.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_fNext_17.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_fNext_18.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_fNext_19.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_fNext_20.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_fNext_21.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_fNext_22.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_fNext_23.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_fNext_24.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_fNext_25.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_fNext_26.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_fNext_27.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_fNext_28.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_fpu_div_fOperands_S0.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_fpu_div_fState_S1.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_fpu_div_fState_S2.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_fpu_div_fState_S3.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_fpu_div_fState_S4.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_fpu_div_fResult_S5.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_acc.rst_tick__clk__1((tUInt8)1u);
	 }
       };

/* Model creation/destruction functions */

void MODEL_mkDivideTest::create_model(tSimStateHdl simHdl, bool master)
{
  sim_hdl = simHdl;
  init_reset_request_counters(sim_hdl);
  mkDivideTest_instance = new MOD_mkDivideTest(sim_hdl, "top", NULL);
  bk_get_or_define_clock(sim_hdl, "CLK");
  if (master)
  {
    bk_alter_clock(sim_hdl, bk_get_clock_by_name(sim_hdl, "CLK"), CLK_LOW, false, 0llu, 5llu, 5llu);
    bk_use_default_reset(sim_hdl);
  }
  bk_set_clock_event_fn(sim_hdl,
			bk_get_clock_by_name(sim_hdl, "CLK"),
			schedule_posedge_CLK,
			NULL,
			(tEdgeDirection)(POSEDGE));
  (mkDivideTest_instance->INST_fpu_madd_fOperand_S0.set_clk_0)("CLK");
  (mkDivideTest_instance->INST_fpu_madd_fState_S1.set_clk_0)("CLK");
  (mkDivideTest_instance->INST_fpu_madd_fState_S2.set_clk_0)("CLK");
  (mkDivideTest_instance->INST_fpu_madd_fProd_S2.set_clk_0)("CLK");
  (mkDivideTest_instance->INST_fpu_madd_fState_S3.set_clk_0)("CLK");
  (mkDivideTest_instance->INST_fpu_madd_fProd_S3.set_clk_0)("CLK");
  (mkDivideTest_instance->INST_fpu_madd_fState_S4.set_clk_0)("CLK");
  (mkDivideTest_instance->INST_fpu_madd_fState_S5.set_clk_0)("CLK");
  (mkDivideTest_instance->INST_fpu_madd_fState_S6.set_clk_0)("CLK");
  (mkDivideTest_instance->INST_fpu_madd_fState_S7.set_clk_0)("CLK");
  (mkDivideTest_instance->INST_fpu_madd_fState_S8.set_clk_0)("CLK");
  (mkDivideTest_instance->INST_fpu_madd_fResult_S9.set_clk_0)("CLK");
  (mkDivideTest_instance->INST_fRequest.set_clk_0)("CLK");
  (mkDivideTest_instance->INST_fResponse.set_clk_0)("CLK");
  (mkDivideTest_instance->INST_fFirst.set_clk_0)("CLK");
  (mkDivideTest_instance->INST_fNext_0.set_clk_0)("CLK");
  (mkDivideTest_instance->INST_fNext_1.set_clk_0)("CLK");
  (mkDivideTest_instance->INST_fNext_2.set_clk_0)("CLK");
  (mkDivideTest_instance->INST_fNext_3.set_clk_0)("CLK");
  (mkDivideTest_instance->INST_fNext_4.set_clk_0)("CLK");
  (mkDivideTest_instance->INST_fNext_5.set_clk_0)("CLK");
  (mkDivideTest_instance->INST_fNext_6.set_clk_0)("CLK");
  (mkDivideTest_instance->INST_fNext_7.set_clk_0)("CLK");
  (mkDivideTest_instance->INST_fNext_8.set_clk_0)("CLK");
  (mkDivideTest_instance->INST_fNext_9.set_clk_0)("CLK");
  (mkDivideTest_instance->INST_fNext_10.set_clk_0)("CLK");
  (mkDivideTest_instance->INST_fNext_11.set_clk_0)("CLK");
  (mkDivideTest_instance->INST_fNext_12.set_clk_0)("CLK");
  (mkDivideTest_instance->INST_fNext_13.set_clk_0)("CLK");
  (mkDivideTest_instance->INST_fNext_14.set_clk_0)("CLK");
  (mkDivideTest_instance->INST_fNext_15.set_clk_0)("CLK");
  (mkDivideTest_instance->INST_fNext_16.set_clk_0)("CLK");
  (mkDivideTest_instance->INST_fNext_17.set_clk_0)("CLK");
  (mkDivideTest_instance->INST_fNext_18.set_clk_0)("CLK");
  (mkDivideTest_instance->INST_fNext_19.set_clk_0)("CLK");
  (mkDivideTest_instance->INST_fNext_20.set_clk_0)("CLK");
  (mkDivideTest_instance->INST_fNext_21.set_clk_0)("CLK");
  (mkDivideTest_instance->INST_fNext_22.set_clk_0)("CLK");
  (mkDivideTest_instance->INST_fNext_23.set_clk_0)("CLK");
  (mkDivideTest_instance->INST_fNext_24.set_clk_0)("CLK");
  (mkDivideTest_instance->INST_fNext_25.set_clk_0)("CLK");
  (mkDivideTest_instance->INST_fNext_26.set_clk_0)("CLK");
  (mkDivideTest_instance->INST_fNext_27.set_clk_0)("CLK");
  (mkDivideTest_instance->INST_fNext_28.set_clk_0)("CLK");
  (mkDivideTest_instance->INST_fpu_div_fOperands_S0.set_clk_0)("CLK");
  (mkDivideTest_instance->INST_fpu_div_fState_S1.set_clk_0)("CLK");
  (mkDivideTest_instance->INST_fpu_div_fState_S2.set_clk_0)("CLK");
  (mkDivideTest_instance->INST_fpu_div_fState_S3.set_clk_0)("CLK");
  (mkDivideTest_instance->INST_fpu_div_fState_S4.set_clk_0)("CLK");
  (mkDivideTest_instance->INST_fpu_div_fResult_S5.set_clk_0)("CLK");
  (mkDivideTest_instance->set_clk_0)("CLK");
}
void MODEL_mkDivideTest::destroy_model()
{
  delete mkDivideTest_instance;
  mkDivideTest_instance = NULL;
}
void MODEL_mkDivideTest::reset_model(bool asserted)
{
  (mkDivideTest_instance->reset_RST_N)(asserted ? (tUInt8)0u : (tUInt8)1u);
}
void * MODEL_mkDivideTest::get_instance()
{
  return mkDivideTest_instance;
}

/* Fill in version numbers */
void MODEL_mkDivideTest::get_version(unsigned int *year,
				     unsigned int *month,
				     char const **annotation,
				     char const **build)
{
  *year = 0u;
  *month = 0u;
  *annotation = NULL;
  *build = "399b09c";
}

/* Get the model creation time */
time_t MODEL_mkDivideTest::get_creation_time()
{
  
  /* Fri Apr  2 14:25:05 UTC 2021 */
  return 1617373505llu;
}

/* State dumping function */
void MODEL_mkDivideTest::dump_state()
{
  (mkDivideTest_instance->dump_state)(0u);
}

/* VCD dumping functions */
MOD_mkDivideTest & mkDivideTest_backing(tSimStateHdl simHdl)
{
  static MOD_mkDivideTest *instance = NULL;
  if (instance == NULL)
  {
    vcd_set_backing_instance(simHdl, true);
    instance = new MOD_mkDivideTest(simHdl, "top", NULL);
    vcd_set_backing_instance(simHdl, false);
  }
  return *instance;
}
void MODEL_mkDivideTest::dump_VCD_defs()
{
  (mkDivideTest_instance->dump_VCD_defs)(vcd_depth(sim_hdl));
}
void MODEL_mkDivideTest::dump_VCD(tVCDDumpType dt)
{
  (mkDivideTest_instance->dump_VCD)(dt, vcd_depth(sim_hdl), mkDivideTest_backing(sim_hdl));
}
